# Generated by Django 3.2.5 on 2021-07-30 08:00

from django.db import migrations, models
import location_field.models.plain
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('avsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63),
        ),
        migrations.AddField(
            model_name='consultant',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='consultant',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63),
        ),
        migrations.AlterField(
            model_name='client',
            name='business_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
