# Generated by Django 3.2.5 on 2021-10-19 09:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('avsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceinvitation',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('817838c4-427e-46a6-bd5e-ac3bfd859f70'), editable=False, unique=True),
        ),
    ]
