# Generated by Django 3.2.5 on 2021-09-14 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='allow_grad_consult',
        ),
        migrations.RemoveField(
            model_name='client',
            name='consult_location',
        ),
        migrations.RemoveField(
            model_name='client',
            name='priority_consult_cost',
        ),
        migrations.RemoveField(
            model_name='client',
            name='priority_consult_exp',
        ),
        migrations.RemoveField(
            model_name='client',
            name='priority_consult_loc',
        ),
        migrations.RemoveField(
            model_name='client',
            name='priority_consult_rating',
        ),
        migrations.RemoveField(
            model_name='client',
            name='priority_project_date',
        ),
        migrations.RemoveField(
            model_name='client',
            name='proj_area',
        ),
        migrations.RemoveField(
            model_name='client',
            name='proj_details',
        ),
        migrations.RemoveField(
            model_name='client',
            name='proj_end_date',
        ),
        migrations.RemoveField(
            model_name='client',
            name='proj_flex',
        ),
        migrations.RemoveField(
            model_name='client',
            name='proj_obj',
        ),
        migrations.RemoveField(
            model_name='client',
            name='proj_spec_service',
        ),
        migrations.RemoveField(
            model_name='client',
            name='proj_start_date',
        ),
        migrations.CreateModel(
            name='ClientServiceEnquiryForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('proj_obj', models.TextField(verbose_name='What are your objectives for the project?')),
                ('proj_area', models.CharField(max_length=200, verbose_name='What area of sustainability are you looking for services in?')),
                ('proj_spec_service', models.CharField(max_length=200, verbose_name='Identify specific services you are looking for')),
                ('proj_start_date', models.DateField(help_text='Please specify project dates (even if approximately)', verbose_name='Start date')),
                ('proj_end_date', models.DateField(help_text='Please specify project dates (even if approximately)', verbose_name='End date')),
                ('proj_flex', models.CharField(choices=[('1', 'Yes, quite flexible'), ('2', 'Some flexibility'), ('0', 'No, not flexible at all')], max_length=1, verbose_name='Are the start and end dates flexible?')),
                ('proj_details', models.TextField(max_length=1000, verbose_name='Describe in detail what kind of work you need to be done. Please be as specific as possible, so that we can find the best suitable consultant for you.')),
                ('consult_location', models.CharField(max_length=200, verbose_name='Please specify where the consultant should be located')),
                ('allow_grad_consult', models.CharField(choices=[('1', 'Yes'), ('2', 'No')], max_length=1, verbose_name='Would you agree to work with a graduate consultant if senior consultants aren’t available for your project or specific dates? ')),
                ('priority_consult_exp', models.CharField(choices=[('1', '1-Extremely Important'), ('2', '2-Fairly important'), ('3', '3-Important'), ('4', '4-Slightly Important'), ('5', '5-Least important')], max_length=1, verbose_name='Consultant experience')),
                ('priority_consult_loc', models.CharField(choices=[('1', '1-Extremely Important'), ('2', '2-Fairly important'), ('3', '3-Important'), ('4', '4-Slightly Important'), ('5', '5-Least important')], max_length=1, verbose_name='Consultant location')),
                ('priority_consult_cost', models.CharField(choices=[('1', '1-Extremely Important'), ('2', '2-Fairly important'), ('3', '3-Important'), ('4', '4-Slightly Important'), ('5', '5-Least important')], max_length=1, verbose_name='Cost of the work')),
                ('priority_project_date', models.CharField(choices=[('1', '1-Extremely Important'), ('2', '2-Fairly important'), ('3', '3-Important'), ('4', '4-Slightly Important'), ('5', '5-Least important')], max_length=1, verbose_name='Dates of the project')),
                ('priority_consult_rating', models.CharField(choices=[('1', '1-Extremely Important'), ('2', '2-Fairly important'), ('3', '3-Important'), ('4', '4-Slightly Important'), ('5', '5-Least important')], max_length=1, verbose_name='Consultant Satisfaction Rating/feedback from previous clients')),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avsapp.client')),
            ],
        ),
    ]
