# Generated by Django 3.2.5 on 2021-10-31 09:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('avsapp', '0002_alter_serviceinvitation_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='aggrement_service',
        ),
        migrations.RemoveField(
            model_name='consultant',
            name='aggrement_service',
        ),
        migrations.AlterField(
            model_name='client',
            name='aggrement_plociy',
            field=models.BooleanField(default=False, verbose_name='Terms and Conditions'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='aggrement_plociy',
            field=models.BooleanField(default=False, verbose_name='Terms and Conditions'),
        ),
        migrations.AlterField(
            model_name='serviceinvitation',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('8d1217c9-c4c5-493c-8863-43d065097c88'), editable=False, unique=True),
        ),
    ]
