# Generated by Django 3.2.5 on 2021-08-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avsapp', '0002_auto_20210730_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
        ),
    ]
